object AppLibs {
    const val coreKtx = "androidx.core:core-ktx:${AppLibsVersions.coreKtx}"
    const val appCompat = "androidx.appcompat:appcompat:${AppLibsVersions.appCompat}"
    const val viewModel = "androidx.lifecycle:lifecycle-viewmodel-ktx:${AppLibsVersions.lifecycle}"
    const val viewModelCompose = "androidx.lifecycle:lifecycle-viewmodel-compose:${AppLibsVersions.lifecycle}"
    const val hilt = "com.google.dagger:hilt-android:${AppLibsVersions.hilt}"
    const val hiltPlugin = "com.google.dagger.hilt.android"
    const val hiltCompiler = "com.google.dagger:hilt-compiler:${AppLibsVersions.hilt}"
    const val hiltNavigationCompose = "androidx.hilt:hilt-navigation-compose:${AppLibsVersions.hiltNavigationCompose}"
    const val composeBOM = "androidx.compose:compose-bom:${AppLibsVersions.composeBOM}"
    const val composeToolingPreview = "androidx.compose.ui:ui-tooling-preview"
    const val composeTooling = "androidx.compose.ui:ui-tooling"
    const val composeMaterial = "androidx.compose.material3:material3"
    const val composeMaterialIcon = "androidx.compose.material:material-icons-extended:${AppLibsVersions.composeMaterialIcon}"
    const val composeActivity = "androidx.activity:activity-compose:${AppLibsVersions.composeActivity}"
    const val composeNavigation = "androidx.navigation:navigation-compose:${AppLibsVersions.composeNavigation}"
    const val composeConstraintLayout = "androidx.constraintlayout:constraintlayout-compose:${AppLibsVersions.composeConstraintLayout}"
    const val coroutines = "org.jetbrains.kotlinx:kotlinx-coroutines-android:${AppLibsVersions.coroutines}"
    const val retrofit = "com.squareup.retrofit2:retrofit:${AppLibsVersions.retrofit}"
    const val kotlinSerializationPlugin = "org.jetbrains.kotlin.plugin.serialization"
    const val kotlinSerialization = "org.jetbrains.kotlinx:kotlinx-serialization-json:${AppLibsVersions.kotlinSerialization}"
    const val kotlinSerializationConverter = "com.jakewharton.retrofit:retrofit2-kotlinx-serialization-converter:${AppLibsVersions.kotlinSerializationConverter}"
    const val kotlinParcelizePlugin = "kotlin-parcelize"
    const val okHttp = "com.squareup.okhttp3:okhttp:${AppLibsVersions.okHttp}"
    const val okHttpLogging = "com.squareup.okhttp3:logging-interceptor:${AppLibsVersions.okHttp}"
    const val coil = "io.coil-kt:coil-compose:${AppLibsVersions.coil}"
    const val material = "com.google.android.material:material:${AppLibsVersions.material}"
    const val pagingCompose = "androidx.paging:paging-compose:${AppLibsVersions.paging}"
    const val paging = "androidx.paging:paging-runtime:${AppLibsVersions.paging}"
}

object AppLibsVersions {
    const val coreKtx = "1.9.0"
    const val appCompat = "1.6.0"
    const val lifecycle = "2.5.1"
    const val hilt = "2.44.2"
    const val hiltNavigationCompose = "1.0.0"
    const val composeBOM = "2022.12.00"
    const val composeCompiler = "1.4.0"
    const val composeActivity = "1.5.1"
    const val composeNavigation = "2.5.3"
    const val composeConstraintLayout = "1.0.1"
    const val composeMaterialIcon = "1.3.1"
    const val coroutines = "1.6.4"
    const val retrofit = "2.9.0"
    const val kotlinSerialization = "1.4.1"
    const val kotlinSerializationConverter = "0.8.0"
    const val okHttp = "4.10.0"
    const val coil = "2.2.2"
    const val material = "1.7.0"
    const val paging = "3.2.1"
}